#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "XrmToolBox Tool Library submission (ticket #6)"

note "Icon artwork (32x32 + 80x80) and the .nuspec Project URL are already"
note "in place — Plugin.cs has both base64 images filled in, and the nuspec"
note "already points at the public repo. This wizard only covers the four"
note "steps that need YOUR own NuGet.org / XrmToolBox-portal accounts."
pause

# ── Stage 1: NuGet.org account + API key ──────────────────────────────────
stage "NuGet.org account + publish API key"
say "You need your own NuGet.org account to own/push this package."
open_url "https://www.nuget.org/users/account/LogOn"
step "Sign in (or 'Register' if you don't have an account yet)."
pause "Signed in?"
open_url "https://www.nuget.org/account/apikeys"
step "Click 'Create'."
step "Give it a name, e.g. 'BuMatrixSecurityRoleAssigner-push'."
step "Glob pattern: scope it to just this package id, 'BuMatrixSecurityRoleAssigner*',"
step "  rather than leaving it unscoped across all your packages."
step "Select scope 'Push new packages and package versions' (Push-only is enough;"
step "  you don't need Unlist/Delete)."
step "Click 'Create', then copy the key — NuGet only shows it once."
ask_secret NUGET_API_KEY "Paste the NuGet API key:"
write_env NUGET_API_KEY "$NUGET_API_KEY"
warn "This key lives only in .env on this machine (gitignored) — never commit it."

# ── Stage 2: build + pack the .nupkg ───────────────────────────────────────
stage "Build and pack the .nupkg"
say "Packing uses BuMatrixSecurityRoleAssigner.nuspec, which needs a real"
say "version substituted for its \$version\$ token."
ask NUGET_PACKAGE_VERSION "Package version to publish (must match the plugin's AssemblyVersion, e.g. 1.0.0):"
write_env NUGET_PACKAGE_VERSION "$NUGET_PACKAGE_VERSION"

if confirm "Run 'dotnet build -c Release' now to produce fresh DLLs?"; then
  ( cd "$(dirname "$0")/.." && dotnet build -c Release ) \
    && say "${GREEN}✓ build succeeded${RESET}" \
    || { warn "build failed — fix it, then re-run this wizard"; exit 1; }
else
  SKIPPED+=("dotnet build -c Release — run it before packing")
fi

if command -v nuget >/dev/null 2>&1; then
  if confirm "Run 'nuget pack' now with version $NUGET_PACKAGE_VERSION?"; then
    ( cd "$(dirname "$0")/.." && nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version "$NUGET_PACKAGE_VERSION" -OutputDirectory nupkg ) \
      && say "${GREEN}✓ packed to nupkg/${RESET}" \
      || { warn "pack failed"; exit 1; }
  else
    SKIPPED+=("nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg")
  fi
else
  warn "classic 'nuget' CLI not found on PATH — nuspec-driven packing (with the <files> section) needs it, not 'dotnet pack'."
  step "Install it (e.g. 'winget install NuGet.CommandLine' or download nuget.exe from nuget.org), then run:"
  note "  nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg"
  SKIPPED+=("install nuget.exe, then: nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg")
fi

say "Sanity-check the .nupkg before pushing (rename a copy to .zip and open it, or use NuGet Package Explorer):"
step "  DLLs land under lib\\net48\\Plugins\\ (not loose at the package root)."
step "  No stray XrmToolBox/SDK/host DLLs bundled alongside your two DLLs."
pause "Checked the package contents?"

# ── Stage 3: push to NuGet.org ─────────────────────────────────────────────
stage "Push to NuGet.org"
NUPKG_PATH="nupkg/BuMatrixSecurityRoleAssigner.${NUGET_PACKAGE_VERSION}.nupkg"
say "About to push:"
note "  $NUPKG_PATH"
say "This publishes publicly and immutably at this version — you can unlist"
say "later but never truly delete or reuse the version number."
if [[ -f "$(dirname "$0")/../$NUPKG_PATH" ]] && command -v nuget >/dev/null 2>&1; then
  if confirm "Push $NUPKG_PATH to NuGet.org now?"; then
    ( cd "$(dirname "$0")/.." && nuget push "$NUPKG_PATH" -Source https://api.nuget.org/v3/index.json -ApiKey "$NUGET_API_KEY" ) \
      && say "${GREEN}✓ pushed${RESET}" \
      || { warn "push failed — check the API key scope/expiry and re-run"; exit 1; }
  else
    SKIPPED+=("nuget push $NUPKG_PATH -Source https://api.nuget.org/v3/index.json -ApiKey <your key>")
  fi
else
  warn "couldn't find $NUPKG_PATH (or 'nuget' isn't on PATH) — push it yourself once packed:"
  note "  nuget push $NUPKG_PATH -Source https://api.nuget.org/v3/index.json -ApiKey <your key>"
  SKIPPED+=("nuget push $NUPKG_PATH -Source https://api.nuget.org/v3/index.json -ApiKey <your key>")
fi
open_url "https://www.nuget.org/packages/BuMatrixSecurityRoleAssigner"
step "Confirm the package page is live (indexing can take a couple of minutes)."
pause "Package visible on NuGet.org?"

# ── Stage 4: XrmToolBox portal account + package registration ─────────────
stage "XrmToolBox portal account + package registration"
say "Separate account from NuGet.org — this is what triggers the manual"
say "admin review (docs say 'can take a few days')."
open_url "https://www.xrmtoolbox.com/login/"
step "Sign in, or create an account if you don't have one yet."
pause "Signed in to the XrmToolBox portal?"
open_url "https://www.xrmtoolbox.com/plugins/new/"
step "Register the package id 'BuMatrixSecurityRoleAssigner' (must match the"
step "  <id> in BuMatrixSecurityRoleAssigner.nuspec exactly) — the portal parses"
step "  metadata straight from NuGet.org, no manual field entry needed."
step "Submit for review."
if confirm "Package id registered and submitted for review?"; then
  write_env XRMTOOLBOX_PACKAGE_REGISTERED "true"
else
  SKIPPED+=("register package id 'BuMatrixSecurityRoleAssigner' at xrmtoolbox.com/plugins/new/")
fi
note "Review turnaround is a few days per xrmtoolbox.com docs — no further action needed until then."

finish
