# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill (PowerShell port of the bash template).
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

$script:TotalStages = 0
$script:StageIndex = 0
$script:EnvFile = if ($env:WIZARD_ENV_FILE) { $env:WIZARD_ENV_FILE } else { Join-Path $PSScriptRoot '..\.env' }
$script:WrittenEnv = @()
$script:WrittenSecret = @()
$script:Skipped = @()

function Clear-WizardScreen {
  if ([Console]::IsOutputRedirected) { return }
  Clear-Host
}

function Show-Banner {
  param([string]$Title)
  Clear-WizardScreen
  Write-Host ""
  Write-Host "  $Title" -ForegroundColor Blue -NoNewline
  Write-Host ""
  Write-Host "  $($script:TotalStages) stages" -ForegroundColor DarkGray
  Write-Host ""
  Write-Host "  You drive the browser; this wizard tells you exactly what to do and" -ForegroundColor DarkGray
  Write-Host "  captures the values you copy back. Stop any time with Ctrl-C and re-run" -ForegroundColor DarkGray
  Write-Host "  later - it remembers values already saved." -ForegroundColor DarkGray
  Wait-ForEnter "Ready to start?"
}

function Start-Stage {
  param([string]$Name)
  Clear-WizardScreen
  $script:StageIndex++
  Write-Host ""
  Write-Host "  > Stage $($script:StageIndex)/$($script:TotalStages) . $Name" -ForegroundColor Blue
}

function Say([string]$Text)  { Write-Host "  $Text" }
function Step([string]$Text) { Write-Host "  - $Text" -ForegroundColor Blue }
function Note([string]$Text) { Write-Host "  $Text" -ForegroundColor DarkGray }
function Warn([string]$Text) { Write-Host "  ! $Text" -ForegroundColor Yellow }

function Open-WizardUrl {
  param([string]$Url)
  Write-Host "  -> opening " -ForegroundColor Green -NoNewline
  Write-Host $Url
  try { Start-Process $Url | Out-Null }
  catch { Warn "couldn't open a browser - visit it manually: $Url" }
}

function Wait-ForEnter {
  param([string]$Message = "Press Enter to continue")
  Write-Host "  $Message " -ForegroundColor DarkGray -NoNewline
  [void](Read-Host)
}

function Confirm-Wizard {
  param([string]$Question)
  Write-Host "  ? $Question [y/N] " -ForegroundColor Yellow -NoNewline
  $reply = Read-Host
  return $reply -match '^[Yy]'
}

function Get-ExistingEnvValue {
  param([string]$Key)
  if (-not (Test-Path $script:EnvFile)) { return $null }
  $line = Get-Content $script:EnvFile | Where-Object { $_ -match "^$Key=" } | Select-Object -Last 1
  if (-not $line) { return $null }
  return $line.Substring($Key.Length + 1)
}

function Read-WizardValue {
  param([string]$Key, [string]$Prompt)
  $current = Get-ExistingEnvValue -Key $Key
  if ($current) {
    Write-Host "  $Prompt " -ForegroundColor White -NoNewline
    Write-Host "[Enter keeps current] " -ForegroundColor DarkGray -NoNewline
  } else {
    Write-Host "  $Prompt " -ForegroundColor White -NoNewline
  }
  $input = Read-Host
  if ([string]::IsNullOrEmpty($input) -and $current) { $input = $current }
  Set-Variable -Name $Key -Value $input -Scope Script
  return $input
}

function Read-WizardSecret {
  param([string]$Key, [string]$Prompt)
  $current = Get-ExistingEnvValue -Key $Key
  if ($current) {
    Write-Host "  $Prompt " -ForegroundColor White -NoNewline
    Write-Host "[Enter keeps current] " -ForegroundColor DarkGray -NoNewline
  } else {
    Write-Host "  $Prompt " -ForegroundColor White -NoNewline
  }
  $secure = Read-Host -AsSecureString
  $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  $input = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
  [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  if ([string]::IsNullOrEmpty($input) -and $current) { $input = $current }
  Set-Variable -Name $Key -Value $input -Scope Script
  return $input
}

function Write-WizardEnv {
  param([string]$Key, [string]$Value)
  $existingLines = @()
  if (Test-Path $script:EnvFile) {
    $existingLines = Get-Content $script:EnvFile | Where-Object { $_ -notmatch "^$Key=" }
  }
  $existingLines + "$Key=$Value" | Set-Content $script:EnvFile
  $script:WrittenEnv += $Key
  Write-Host "  " -NoNewline
  Write-Host "OK wrote " -ForegroundColor Green -NoNewline
  Write-Host "$Key -> $($script:EnvFile)"
}

function Set-WizardSecret {
  param([string]$Name, [string]$Value)
  $ghAvailable = Get-Command gh -ErrorAction SilentlyContinue
  if ($ghAvailable) {
    try {
      gh auth status *> $null
      $Value | gh secret set $Name *> $null
      $script:WrittenSecret += $Name
      Write-Host "  " -NoNewline
      Write-Host "OK set " -ForegroundColor Green -NoNewline
      Write-Host "GitHub secret $Name"
      return
    } catch { }
  }
  $script:Skipped += "GitHub secret $Name (set it manually: gh secret set $Name)"
  Warn "skipped GitHub secret $Name - gh not ready; set it later"
}

function Complete-Wizard {
  Clear-WizardScreen
  Write-Host ""
  Write-Host "  OK Setup complete" -ForegroundColor Green
  if ($script:WrittenEnv.Count -gt 0) {
    Note "wrote $($script:WrittenEnv.Count) value(s) to $($script:EnvFile): $($script:WrittenEnv -join ', ')"
  }
  if ($script:WrittenSecret.Count -gt 0) {
    Note "set $($script:WrittenSecret.Count) GitHub secret(s): $($script:WrittenSecret -join ', ')"
  }
  if ($script:Skipped.Count -gt 0) {
    Write-Host ""
    Warn "still to do by hand:"
    foreach ($s in $script:Skipped) { Note "  - $s" }
  }
  Write-Host ""
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One Start-Stage per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$script:TotalStages = 4

Show-Banner "XrmToolBox Tool Library submission (ticket #6)"

Note "Icon artwork (32x32 + 80x80) and the .nuspec Project URL are already"
Note "in place - Plugin.cs has both base64 images filled in, and the nuspec"
Note "already points at the public repo. This wizard only covers the four"
Note "steps that need YOUR own NuGet.org / XrmToolBox-portal accounts."
Wait-ForEnter

# ── Stage 1: NuGet.org account + API key ──────────────────────────────────
Start-Stage "NuGet.org account + publish API key"
Say "You need your own NuGet.org account to own/push this package."
Open-WizardUrl "https://www.nuget.org/users/account/LogOn"
Step "Sign in (or 'Register' if you don't have an account yet)."
Wait-ForEnter "Signed in?"
Open-WizardUrl "https://www.nuget.org/account/apikeys"
Step "Click 'Create'."
Step "Give it a name, e.g. 'BuMatrixSecurityRoleAssigner-push'."
Step "Glob pattern: scope it to just this package id, 'BuMatrixSecurityRoleAssigner*',"
Step "  rather than leaving it unscoped across all your packages."
Step "Select scope 'Push new packages and package versions' (Push-only is enough;"
Step "  you don't need Unlist/Delete)."
Step "Click 'Create', then copy the key - NuGet only shows it once."
$NUGET_API_KEY = Read-WizardSecret -Key 'NUGET_API_KEY' -Prompt "Paste the NuGet API key:"
Write-WizardEnv -Key 'NUGET_API_KEY' -Value $NUGET_API_KEY
Warn "This key lives only in .env on this machine (gitignored) - never commit it."

# ── Stage 2: build + pack the .nupkg ───────────────────────────────────────
Start-Stage "Build and pack the .nupkg"
Say "Packing uses BuMatrixSecurityRoleAssigner.nuspec, which needs a real"
Say "version substituted for its `$version`$ token."
$NUGET_PACKAGE_VERSION = Read-WizardValue -Key 'NUGET_PACKAGE_VERSION' -Prompt "Package version to publish (must match the plugin's AssemblyVersion, e.g. 1.0.0):"
Write-WizardEnv -Key 'NUGET_PACKAGE_VERSION' -Value $NUGET_PACKAGE_VERSION

if (Confirm-Wizard "Run 'dotnet build -c Release' now to produce fresh DLLs?") {
  Push-Location $RepoRoot
  try {
    dotnet build -c Release
    Write-Host "  OK build succeeded" -ForegroundColor Green
  } catch {
    Warn "build failed - fix it, then re-run this wizard"
    Pop-Location
    exit 1
  }
  Pop-Location
} else {
  $script:Skipped += "dotnet build -c Release - run it before packing"
}

$nugetCli = Get-Command nuget -ErrorAction SilentlyContinue
if ($nugetCli) {
  if (Confirm-Wizard "Run 'nuget pack' now with version $NUGET_PACKAGE_VERSION?") {
    Push-Location $RepoRoot
    try {
      nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg
      Write-Host "  OK packed to nupkg/" -ForegroundColor Green
    } catch {
      Warn "pack failed"
      Pop-Location
      exit 1
    }
    Pop-Location
  } else {
    $script:Skipped += "nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg"
  }
} else {
  Warn "classic 'nuget' CLI not found on PATH - nuspec-driven packing (with the <files> section) needs it, not 'dotnet pack'."
  Step "Install it (e.g. 'winget install NuGet.CommandLine' or download nuget.exe from nuget.org), then run:"
  Note "  nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg"
  $script:Skipped += "install nuget.exe, then: nuget pack BuMatrixSecurityRoleAssigner.nuspec -Version $NUGET_PACKAGE_VERSION -OutputDirectory nupkg"
}

Say "Sanity-check the .nupkg before pushing (rename a copy to .zip and open it, or use NuGet Package Explorer):"
Step "  DLLs land under lib\net48\Plugins\ (not loose at the package root)."
Step "  No stray XrmToolBox/SDK/host DLLs bundled alongside your two DLLs."
Wait-ForEnter "Checked the package contents?"

# ── Stage 3: push to NuGet.org ─────────────────────────────────────────────
Start-Stage "Push to NuGet.org"
$NupkgPath = "nupkg\BuMatrixSecurityRoleAssigner.$NUGET_PACKAGE_VERSION.nupkg"
Say "About to push:"
Note "  $NupkgPath"
Say "This publishes publicly and immutably at this version - you can unlist"
Say "later but never truly delete or reuse the version number."
$fullNupkgPath = Join-Path $RepoRoot $NupkgPath
if ((Test-Path $fullNupkgPath) -and $nugetCli) {
  if (Confirm-Wizard "Push $NupkgPath to NuGet.org now?") {
    Push-Location $RepoRoot
    try {
      nuget push $NupkgPath -Source https://api.nuget.org/v3/index.json -ApiKey $NUGET_API_KEY
      Write-Host "  OK pushed" -ForegroundColor Green
    } catch {
      Warn "push failed - check the API key scope/expiry and re-run"
      Pop-Location
      exit 1
    }
    Pop-Location
  } else {
    $script:Skipped += "nuget push $NupkgPath -Source https://api.nuget.org/v3/index.json -ApiKey <your key>"
  }
} else {
  Warn "couldn't find $NupkgPath (or 'nuget' isn't on PATH) - push it yourself once packed:"
  Note "  nuget push $NupkgPath -Source https://api.nuget.org/v3/index.json -ApiKey <your key>"
  $script:Skipped += "nuget push $NupkgPath -Source https://api.nuget.org/v3/index.json -ApiKey <your key>"
}
Open-WizardUrl "https://www.nuget.org/packages/BuMatrixSecurityRoleAssigner"
Step "Confirm the package page is live (indexing can take a couple of minutes)."
Wait-ForEnter "Package visible on NuGet.org?"

# ── Stage 4: XrmToolBox portal account + package registration ─────────────
Start-Stage "XrmToolBox portal account + package registration"
Say "Separate account from NuGet.org - this is what triggers the manual"
Say "admin review (docs say 'can take a few days')."
Open-WizardUrl "https://www.xrmtoolbox.com/login/"
Step "Sign in, or create an account if you don't have one yet."
Wait-ForEnter "Signed in to the XrmToolBox portal?"
Open-WizardUrl "https://www.xrmtoolbox.com/plugins/register/"
Step "Register the package id 'BuMatrixSecurityRoleAssigner' (must match the"
Step "  <id> in BuMatrixSecurityRoleAssigner.nuspec exactly)."
Step "Submit for review."
if (Confirm-Wizard "Package id registered and submitted for review?") {
  Write-WizardEnv -Key 'XRMTOOLBOX_PACKAGE_REGISTERED' -Value 'true'
} else {
  $script:Skipped += "register package id 'BuMatrixSecurityRoleAssigner' at xrmtoolbox.com/plugins/register/"
}
Note "Review turnaround is a few days per xrmtoolbox.com docs - no further action needed until then."

Complete-Wizard
