#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "XrmToolBox Tool Library submission setup"

# ── Stage 1: NuGet.org Trusted Publishing policy ────────────────────────────
stage "NuGet.org — Trusted Publishing policy"
say "nuget.org now steers new accounts toward Trusted Publishing (OIDC via"
say "GitHub Actions) instead of long-lived classic API keys — no secret to"
say "manage or leak. A workflow now exists in this repo: publish-nuget.yml."
open_url "https://www.nuget.org/account/trustedpublishing"
step "If you already created policies here, DELETE any broad one with Glob Pattern '*' — it would trust the workflow to push ANY package you own."
step "On the remaining (or a new) policy, set these fields exactly:"
step "  Repository Owner: martintoelk   <- your GitHub LOGIN, not your display name 'Martin Tölk'"
step "  Repository:       Modernized-BU-Security-Role-Assigner"
step "  Workflow File:    publish-nuget.yml   <- filename only, no path"
step "  Glob Pattern:     BuMatrixSecurityRoleAssigner   <- must match the package Id below"
step "Save. It stays 'pending' (7-day window) until the workflow runs once and successfully pushes a package."
pause "Policy fields corrected and saved?"
note "No API key to capture here — the workflow exchanges a short-lived one at run time."

# ── Stage 2: package Id ─────────────────────────────────────────────────────
stage "Pick the NuGet package Id"
say "This is the literal Id nuget.org and the XrmToolBox portal will both use to"
say "identify the plugin. Convention: no spaces, matches the assembly name."
say "Suggested: BuMatrixSecurityRoleAssigner (matches the rewrite's new plugin name)."
ask NUGET_PACKAGE_ID "Package Id to use [Enter for BuMatrixSecurityRoleAssigner]:"
NUGET_PACKAGE_ID="${NUGET_PACKAGE_ID:-BuMatrixSecurityRoleAssigner}"
write_env NUGET_PACKAGE_ID "$NUGET_PACKAGE_ID"
note "The build session's .nuspec should set <id>${NUGET_PACKAGE_ID}</id> to match."

# ── Stage 3: public project URL ─────────────────────────────────────────────
stage "Confirm the public Project URL"
say "The .nuspec needs a public <projectUrl>. The repo is already public."
NUGET_PROJECT_URL_DEFAULT="https://github.com/martintoelk/Modernized-BU-Security-Role-Assigner"
ask NUGET_PROJECT_URL "Project URL to use [Enter for ${NUGET_PROJECT_URL_DEFAULT}]:"
NUGET_PROJECT_URL="${NUGET_PROJECT_URL:-$NUGET_PROJECT_URL_DEFAULT}"
write_env NUGET_PROJECT_URL "$NUGET_PROJECT_URL"

# ── Stage 4: XrmToolBox portal account ──────────────────────────────────────
stage "XrmToolBox portal — account"
say "Separate account from NuGet.org — this is what an admin reviews your"
say "submission under."
open_url "https://www.xrmtoolbox.com/SignIn"
step "Sign in, or register a new account if you don't have one."
pause "Signed in to the XrmToolBox portal?"

# ── Stage 5: register the package for review ────────────────────────────────
stage "Register the package on the XrmToolBox portal"
warn "This step needs the package LIVE on nuget.org first — it doesn't exist yet."
say "BuMatrixSecurityRoleAssigner.nuspec exists (Id: ${NUGET_PACKAGE_ID}), and .github/workflows/publish-nuget.yml"
say "can pack + push it via Trusted Publishing. Still TODO before it can run for real:"
say "  - confirm the min XrmToolBox host version in the nuspec's <dependency> (marked TODO)"
say "  - resolve the open decisions in CLAUDE.md (rename, classic-BU toggle, Core/UI split)"
say "Once ready: Actions tab -> 'Publish NuGet package' -> Run workflow -> enter a version."
if confirm "Is ${NUGET_PACKAGE_ID} already live on nuget.org (nuget.org/packages/${NUGET_PACKAGE_ID})?"; then
  open_url "https://www.xrmtoolbox.com/plugins/new/"
  step "Enter the package Id (${NUGET_PACKAGE_ID}) — the portal auto-parses metadata from NuGet."
  step "Submit. An admin reviews it manually; approval can take a few days."
  pause "Submitted for review?"
else
  SKIPPED+=("Register ${NUGET_PACKAGE_ID} at https://www.xrmtoolbox.com/plugins/new/ — do this once the build session has pushed the package to nuget.org")
  note "Skipping for now — re-run this wizard (or just visit the URL above) once the package is on nuget.org."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
